In [32]:
import os

import numpy as np
import pandas as pd
import matplotlib.image as img
import matplotlib.patches as patch
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df = pd.read_excel("./metadata.xlsx")

In [34]:
df.head()

,Time,Panel NO.,Panel Name,LUX,TEMP (Celcius),VOLTAGE,CURRENT,POWER
0,morning,3.0,d-1-3-1,1350,27.0,26.97,0.87,23.4639
1,morning,NaN,d-1-3-2,1350,27.0,26.97,0.87,23.4639
2,morning,NaN,d-1-3-3,1350,27.0,26.97,0.87,23.4639
3,morning,NaN,d-1-3-4,1350,27.0,26.97,0.87,23.4639
4,morning,4.0,d-1-4-1,2380,27.1,26.15,0.85,22.2275

In [35]:
images=os.listdir('./sol_dataV2 - Copy')
images=[a.split('.')[0] for a in images]
images

['c-2-11-1',
 'c-2-11-2',
 'c-2-11-3',
 'c-2-11-4',
 'c-2-12-1',
 'c-2-12-2',
 'c-2-12-3',
 'c-2-12-4',
 'c-2-16-1',
 'c-2-16-2',
 'c-2-16-3',
 'c-2-16-4',
 'c-2-20-1',
 'c-2-20-2',
 'c-2-20-3',
 'c-2-20-4',
 'c-2-21-1',
 'c-2-21-2',
 'c-2-21-3',
 'c-2-21-4',
 'c-2-26-1',
 'c-2-26-2',
 'c-2-26-3',
 'c-2-26-4',
 'c-2-27-1',
 'c-2-27-2',
 'c-2-27-3',
 'c-2-27-4',
 'c-2-28-1',
 'c-2-28-2',
 'c-2-28-3',
 'c-2-28-4',
 'c-2-29-1',
 'c-2-29-2',
 'c-2-29-3',
 'c-2-29-4',
 'c-2-3-1',
 'c-2-3-2',
 'c-2-3-3',
 'c-2-3-4',
 'c-2-30-1',
 'c-2-30-2',
 'c-2-30-3',
 'c-2-30-4',
 'c-2-31-1',
 'c-2-31-2',
 'c-2-31-3',
 'c-2-31-4',
 'c-2-32-1',
 'c-2-32-2',
 'c-2-32-3',
 'c-2-32-4',
 'c-2-33-1',
 'c-2-33-2',
 'c-2-33-3',
 'c-2-33-4',
 'c-2-34-1',
 'c-2-34-2',
 'c-2-34-3',
 'c-2-34-4',
 'c-2-35-1',
 'c-2-35-2',
 'c-2-35-3',
 'c-2-35-4',
 'c-2-4-1',
 'c-2-4-2',
 'c-2-4-3',
 'c-2-4-4',
 'c-2-5-1',
 'c-2-5-2',
 'c-2-5-3',
 'c-2-5-4',
 'c-2-6-1',
 'c-2-6-2',
 'c-2-6-3',
 'c-2-6-4',
 'c-2-7-1',
 'c-2-7-2',
 'c-2-7-3',
 'c-2-7-4',
 'c-2-9-1',
 'c-2-9-2',
 'c-2-9-3',
 'c-2-9-4',
 'c-3-11-1',
 'c-3-11-2',
 'c-3-11-3',
 'c-3-11-4',
 'c-3-12-1',
 'c-3-12-2',
 'c-3-12-3',
 'c-3-12-4',
 'c-3-16-1',
 'c-3-16-2',
 'c-3-16-3',
 'c-3-16-4',
 'c-3-20-1',
 'c-3-20-2',
 'c-3-20-3',
 'c-3-20-4',
 'c-3-21-1',
 'c-3-21-2',
 'c-3-21-3',
 'c-3-21-4',
 'c-3-26-1',
 'c-3-26-2',
 'c-3-26-3',
 'c-3-26-4',
 'c-3-27-1',
 'c-3-27-2',
 'c-3-27-3',
 'c-3-27-4',
 'c-3-28-1',
 'c-3-28-2',
 'c-3-28-3',
 'c-3-28-4',
 'c-3-29-1',
 'c-3-29-2',
 'c-3-29-3',
 'c-3-29-4',
 'c-3-3-1',
 'c-3-3-2',
 'c-3-3-3',
 'c-3-3-4',
 'c-3-30-1',
 'c-3-30-2',
 'c-3-30-3',
 'c-3-30-4',
 'c-3-31-1',
 'c-3-31-2',
 'c-3-31-3',
 'c-3-31-4',
 'c-3-32-1',
 'c-3-32-2',
 'c-3-32-3',
 'c-3-32-4',
 'c-3-33-1',
 'c-3-33-2',
 'c-3-33-3',
 'c-3-33-4',
 'c-3-34-1',
 'c-3-34-2',
 'c-3-34-3',
 'c-3-34-4',
 'c-3-35-1',
 'c-3-35-2',
 'c-3-35-3',
 'c-3-35-4',
 'c-3-4-1',
 'c-3-4-2',
 'c-3-4-3',
 'c-3-4-4',
 'c-3-5-1',
 'c-3-5-2',
 'c-3-5-3',
 'c-3-5-4',
 'c-3-6-1',
 'c-3-6-2',
 'c-3-6-3',
 'c-3-6-4',
 'c-3-7-1',
 'c-3-7-2',
 'c-3-7-3',
 'c-3-7-4',
 'c-3-9-1',
 'c-3-9-2',
 'c-3-9-3',
 'c-3-9-4',
 'd-1-11-1',
 'd-1-11-2',
 'd-1-11-3',
 'd-1-11-4',
 'd-1-12-1',
 'd-1-12-2',
 'd-1-12-3',
 'd-1-12-4',
 'd-1-16-1',
 'd-1-16-2',
 'd-1-16-3',
 'd-1-16-4',
 'd-1-20-1',
 'd-1-20-2',
 'd-1-20-3',
 'd-1-20-4',
 'd-1-21-1',
 'd-1-21-2',
 'd-1-21-3',
 'd-1-21-4',
 'd-1-26-1',
 'd-1-26-2',
 'd-1-26-3',
 'd-1-26-4',
 'd-1-27-1',
 'd-1-27-2',
 'd-1-27-3',
 'd-1-27-4',
 'd-1-28-1',
 'd-1-28-2',
 'd-1-28-3',
 'd-1-28-4',
 'd-1-29-1',
 'd-1-29-2',
 'd-1-29-3',
 'd-1-29-4',
 'd-1-3-1',
 'd-1-3-2',
 'd-1-3-3',
 'd-1-3-4',
 'd-1-30-1',
 'd-1-30-2',
 'd-1-30-3',
 'd-1-30-4',
 'd-1-31-1',
 'd-1-31-2',
 'd-1-31-3',
 'd-1-31-4',
 'd-1-32-1',
 'd-1-32-2',
 'd-1-32-3',
 'd-1-32-4',
 'd-1-33-1',
 'd-1-33-2',
 'd-1-33-3',
 'd-1-33-4',
 'd-1-34-1',
 'd-1-34-2',
 'd-1-34-3',
 'd-1-34-4',
 'd-1-35-1',
 'd-1-35-2',
 'd-1-35-3',
 'd-1-35-4',
 'd-1-4-1',
 'd-1-4-2',
 'd-1-4-3',
 'd-1-4-4',
 'd-1-5-1',
 'd-1-5-2',
 'd-1-5-3',
 'd-1-5-4',
 'd-1-6-1',
 'd-1-6-2',
 'd-1-6-3',
 'd-1-6-4',
 'd-1-7-1',
 'd-1-7-2',
 'd-1-7-3',
 'd-1-7-4',
 'd-1-9-1',
 'd-1-9-2',
 'd-1-9-3',
 'd-1-9-4',
 'd-2-11-1',
 'd-2-11-2',
 'd-2-11-3',
 'd-2-11-4',
 'd-2-12-1',
 'd-2-12-2',
 'd-2-12-3',
 'd-2-12-4',
 'd-2-16-1',
 'd-2-16-2',
 'd-2-16-3',
 'd-2-16-4',
 'd-2-20-1',
 'd-2-20-2',
 'd-2-20-3',
 'd-2-20-4',
 'd-2-21-1',
 'd-2-21-2',
 'd-2-21-3',
 'd-2-21-4',
 'd-2-26-1',
 'd-2-26-2',
 'd-2-26-3',
 'd-2-26-4',
 'd-2-27-1',
 'd-2-27-2',
 'd-2-27-3',
 'd-2-27-4',
 'd-2-28-1',
 'd-2-28-2',
 'd-2-28-3',
 'd-2-28-4',
 'd-2-29-1',
 'd-2-29-2',
 'd-2-29-3',
 'd-2-29-4',
 'd-2-3-1',
 'd-2-3-2',
 'd-2-3-3',
 'd-2-3-4',
 'd-2-30-1',
 'd-2-30-2',
 'd-2-30-3',
 'd-2-30-4',
 'd-2-31-1',
 'd-2-31-2',
 'd-2-31-3',
 'd-2-31-4',
 'd-2-32-1',
 'd-2-32-2',
 'd-2-32-3',
 'd-2-32-4',
 'd-2-33-1',
 'd-2-33-2',
 'd-2-33-3',
 'd-2-33-4',
 'd-2-34-1',
 'd-2-34-2',
 'd-2-34-3',
 'd-2-34-4',
 'd-2-35-1',
 'd-2-35-2',
 'd-2-35-3',
 'd-2-35-4',
 'd-2-4-1',
 'd-2-4-2',
 'd-2-4-3',
 'd-2-4-4',
 'd-2-5-1',
 'd-2-5-2',
 'd-2-5-3',
 'd-2-5-4',
 'd-2-6-1',
 'd-2-6-2',
 'd-2-6-3',
 'd-2-6-4',
 'd-2-7-1',
 'd-2-7-2',
 'd-2-7-3',
 'd-2-7-4',
 'd-2-9-1',
 'd-2-9-2',
 'd-2-9-3',
 'd-2-9-4',
 'd-3-11-1',
 'd-3-11-2',
 'd-3-11-3',
 'd-3-11-4',
 'd-3-12-1',
 'd-3-12-2',
 'd-3-12-3',
 'd-3-12-4',
 'd-3-16-1',
 'd-3-16-2',
 'd-3-16-3',
 'd-3-16-4',
 'd-3-20-1',
 'd-3-20-2',
 'd-3-20-3',
 'd-3-20-4',
 'd-3-21-1',
 'd-3-21-2',
 'd-3-21-3',
 'd-3-21-4',
 'd-3-26-1',
 'd-3-26-2',
 'd-3-26-3',
 'd-3-26-4',
 'd-3-27-1',
 'd-3-27-2',
 'd-3-27-3',
 'd-3-27-4',
 'd-3-28-1',
 'd-3-28-2',
 'd-3-28-3',
 'd-3-28-4',
 'd-3-29-1',
 'd-3-29-2',
 'd-3-29-3',
 'd-3-29-4',
 'd-3-3-1',
 'd-3-3-2',
 'd-3-3-3',
 'd-3-3-4',
 'd-3-30-1',
 'd-3-30-2',
 'd-3-30-3',
 'd-3-30-4',
 'd-3-31-1',
 'd-3-31-2',
 'd-3-31-3',
 'd-3-31-4',
 'd-3-32-1',
 'd-3-32-2',
 'd-3-32-3',
 'd-3-32-4',
 'd-3-33-1',
 'd-3-33-2',
 'd-3-33-3',
 'd-3-33-4',
 'd-3-34-1',
 'd-3-34-2',
 'd-3-34-3',
 'd-3-34-4',
 'd-3-35-1',
 'd-3-35-2',
 'd-3-35-3',
 'd-3-35-4',
 'd-3-4-1',
 'd-3-4-2',
 'd-3-4-3',
 'd-3-4-4',
 'd-3-5-1',
 'd-3-5-2',
 'd-3-5-3',
 'd-3-5-4',
 'd-3-6-1',
 'd-3-6-2',
 'd-3-6-3',
 'd-3-6-4',
 'd-3-7-1',
 'd-3-7-2',
 'd-3-7-3',
 'd-3-7-4',
 'd-3-9-1',
 'd-3-9-2',
 'd-3-9-3',
 'd-3-9-4',
 's-1-11-1',
 's-1-11-2',
 's-1-11-3',
 's-1-11-4',
 's-1-12-1',
 's-1-12-2',
 's-1-12-3',
 's-1-12-4',
 's-1-16-1',
 's-1-16-2',
 's-1-16-3',
 's-1-16-4',
 's-1-20-1',
 's-1-20-2',
 's-1-20-3',
 's-1-20-4',
 's-1-21-1',
 's-1-21-2',
 's-1-21-3',
 's-1-21-4',
 's-1-26-1',
 's-1-26-2',
 's-1-26-3',
 's-1-26-4',
 's-1-27-1',
 's-1-27-2',
 's-1-27-3',
 's-1-27-4',
 's-1-28-1',
 's-1-28-2',
 's-1-28-3',
 's-1-28-4',
 's-1-29-1',
 's-1-29-2',
 's-1-29-3',
 's-1-29-4',
 's-1-3-1',
 's-1-3-2',
 's-1-3-3',
 's-1-3-4',
 's-1-30-1',
 's-1-30-2',
 's-1-30-3',
 's-1-30-4',
 's-1-31-1',
 's-1-31-2',
 's-1-31-3',
 's-1-31-4',
 's-1-32-1',
 's-1-32-2',
 's-1-32-3',
 's-1-32-4',
 's-1-33-1',
 's-1-33-2',
 's-1-33-3',
 's-1-33-4',
 's-1-34-1',
 's-1-34-2',
 's-1-34-3',
 's-1-34-4',
 's-1-35-1',
 's-1-35-2',
 's-1-35-3',
 's-1-35-4',
 's-1-4-1',
 's-1-4-2',
 's-1-4-3',
 's-1-4-4',
 's-1-5-1',
 's-1-5-2',
 's-1-5-3',
 's-1-5-4',
 's-1-6-1',
 's-1-6-2',
 's-1-6-3',
 's-1-6-4',
 's-1-7-1',
 's-1-7-2',
 's-1-7-3',
 's-1-7-4',
 's-1-9-1',
 's-1-9-2',
 's-1-9-3',
 's-1-9-4',
 's-2-11-1',
 's-2-11-2',
 's-2-11-3',
 's-2-11-4',
 's-2-12-1',
 's-2-12-2',
 's-2-12-3',
 's-2-12-4',
 's-2-16-1',
 's-2-16-2',
 's-2-16-3',
 's-2-16-4',
 's-2-20-1',
 's-2-20-2',
 's-2-20-3',
 's-2-20-4',
 's-2-21-1',
 's-2-21-2',
 's-2-21-3',
 's-2-21-4',
 's-2-3-1',
 's-2-3-2',
 's-2-3-3',
 's-2-3-4',
 's-2-4-1',
 's-2-4-2',
 's-2-4-3',
 's-2-4-4',
 's-2-5-1',
 's-2-5-2',
 's-2-5-3',
 's-2-5-4',
 's-2-6-1',
 's-2-6-2',
 's-2-6-3',
 's-2-6-4',
 's-2-7-1',
 's-2-7-2',
 's-2-7-3',
 's-2-7-4',
 's-2-9-1',
 's-2-9-2',
 's-2-9-3',
 's-2-9-4',
 's-3-11-1',
 's-3-11-2',
 's-3-11-3',
 's-3-11-4',
 's-3-12-1',
 's-3-12-2',
 's-3-12-3',
 's-3-12-4',
 's-3-16-1',
 's-3-16-2',
 's-3-16-3',
 's-3-16-4',
 's-3-20-1',
 's-3-20-2',
 's-3-20-3',
 's-3-20-4',
 's-3-21-1',
 's-3-21-2',
 's-3-21-3',
 's-3-21-4',
 's-3-3-1',
 's-3-3-2',
 's-3-3-3',
 's-3-3-4',
 's-3-4-1',
 's-3-4-2',
 's-3-4-3',
 's-3-4-4',
 's-3-5-1',
 's-3-5-2',
 's-3-5-3',
 's-3-5-4',
 's-3-6-1',
 's-3-6-2',
 's-3-6-3',
 's-3-6-4',
 's-3-7-1',
 's-3-7-2',
 's-3-7-3',
 's-3-7-4',
 's-3-9-1',
 's-3-9-2',
 's-3-9-3',
 's-3-9-4',
 'w-1-11-1',
 'w-1-11-2',
 'w-1-11-3',
 'w-1-11-4',
 'w-1-12-1',
 'w-1-12-2',
 'w-1-12-3',
 'w-1-12-4',
 'w-1-16-1',
 'w-1-16-2',
 'w-1-16-3',
 'w-1-16-4',
 'w-1-20-1',
 'w-1-20-2',
 'w-1-20-3',
 'w-1-20-4',
 'w-1-21-1',
 'w-1-21-2',
 'w-1-21-3',
 'w-1-21-4',
 'w-1-26-1',
 'w-1-26-2',
 'w-1-26-3',
 'w-1-26-4',
 'w-1-27-1',
 'w-1-27-2',
 'w-1-27-3',
 'w-1-27-4',
 'w-1-28-1',
 'w-1-28-2',
 'w-1-28-3',
 'w-1-28-4',
 'w-1-29-1',
 'w-1-29-2',
 'w-1-29-3',
 'w-1-29-4',
 'w-1-3-1',
 'w-1-3-2',
 'w-1-3-3',
 'w-1-3-4',
 'w-1-30-1',
 'w-1-30-2',
 'w-1-30-3',
 'w-1-30-4',
 'w-1-31-1',
 'w-1-31-2',
 'w-1-31-3',
 'w-1-31-4',
 'w-1-32-1',
 'w-1-32-2',
 'w-1-32-3',
 'w-1-32-4',
 'w-1-33-1',
 'w-1-33-2',
 'w-1-33-3',
 'w-1-33-4',
 'w-1-34-1',
 'w-1-34-2',
 'w-1-34-3',
 'w-1-34-4',
 'w-1-35-1',
 'w-1-35-2',
 'w-1-35-3',
 'w-1-35-4',
 'w-1-4-1',
 'w-1-4-2',
 'w-1-4-3',
 'w-1-4-4',
 'w-1-5-1',
 'w-1-5-2',
 'w-1-5-3',
 'w-1-5-4',
 'w-1-6-1',
 'w-1-6-2',
 'w-1-6-3',
 'w-1-6-4',
 'w-1-7-1',
 'w-1-7-2',
 'w-1-7-3',
 'w-1-7-4',
 'w-1-9-1',
 'w-1-9-2',
 'w-1-9-3',
 'w-1-9-4',
 'w-3-11-1',
 'w-3-11-2',
 'w-3-11-3',
 'w-3-11-4',
 'w-3-12-1',
 'w-3-12-2',
 'w-3-12-3',
 'w-3-12-4',
 'w-3-16-1',
 'w-3-16-2',
 'w-3-16-3',
 'w-3-16-4',
 'w-3-20-1',
 'w-3-20-2',
 'w-3-20-3',
 'w-3-20-4',
 'w-3-21-1',
 'w-3-21-2',
 'w-3-21-3',
 'w-3-21-4',
 'w-3-26-1',
 'w-3-26-2',
 'w-3-26-3',
 'w-3-26-4',
 'w-3-27-1',
 'w-3-27-2',
 'w-3-27-3',
 'w-3-27-4',
 'w-3-28-1',
 'w-3-28-2',
 'w-3-28-3',
 'w-3-28-4',
 'w-3-29-1',
 'w-3-29-2',
 'w-3-29-3',
 'w-3-29-4',
 'w-3-3-1',
 'w-3-3-2',
 'w-3-3-3',
 'w-3-3-4',
 'w-3-30-1',
 'w-3-30-2',
 'w-3-30-3',
 'w-3-30-4',
 'w-3-31-1',
 'w-3-31-2',
 'w-3-31-3',
 'w-3-31-4',
 'w-3-32-1',
 'w-3-32-2',
 'w-3-32-3',
 'w-3-32-4',
 'w-3-33-1',
 'w-3-33-2',
 'w-3-33-3',
 'w-3-33-4',
 'w-3-34-1',
 'w-3-34-2',
 'w-3-34-3',
 'w-3-34-4',
 'w-3-35-1',
 'w-3-35-2',
 'w-3-35-3',
 'w-3-35-4',
 'w-3-4-1',
 'w-3-4-2',
 'w-3-4-3',
 'w-3-4-4',
 'w-3-5-1',
 'w-3-5-2',
 'w-3-5-3',
 'w-3-5-4',
 'w-3-6-1',
 'w-3-6-2',
 'w-3-6-3',
 'w-3-6-4',
 'w-3-7-1',
 'w-3-7-2',
 'w-3-7-3',
 'w-3-7-4',
 'w-3-9-1',
 'w-3-9-2',
 'w-3-9-3',
 'w-3-9-4',
 '~$metadata']

In [36]:
dic={
    'panel_name': [],
    'image_name': [],
    'lebel': [],
    'time':[],
}
for panel_name in df['Panel Name']:
    if panel_name in images:
        dic['image_name'].append(f'{panel_name}.jpg')
    else:
        dic['image_name'].append(None)
    dic['panel_name'].append(panel_name)
    dic['time'].append(panel_name.split('-')[1])
    dic['lebel'].append(panel_name.split('-')[0])
new_df=pd.DataFrame(data=dic)

In [37]:
new_df.head()

  panel_name   image_name lebel time
0    d-1-3-1  d-1-3-1.jpg     d    1
1    d-1-3-2  d-1-3-2.jpg     d    1
2    d-1-3-3  d-1-3-3.jpg     d    1
3    d-1-3-4  d-1-3-4.jpg     d    1
4    d-1-4-1  d-1-4-1.jpg     d    1

In [38]:
new_df=new_df.dropna()

In [39]:
new_df.shape

(759, 4)

In [40]:
new_df.shape

(759, 4)

In [41]:
new_df['lebel'].value_counts()

d    252
s    171
c    168
w    168
Name: lebel, dtype: int64

In [42]:
df['Panel Name'].value_counts()

d-1-3-1     1
s-3-4-2     1
s-2-34-1    1
s-2-34-2    1
s-2-34-3    1
           ..
c-2-4-1     1
c-2-4-2     1
c-2-4-3     1
c-2-4-4     1
w-3-35-4    1
Name: Panel Name, Length: 1008, dtype: int64

In [43]:
new_df.shape

(759, 4)

In [44]:
new_df = new_df.join(df[['LUX', 'TEMP (Celcius)']])

In [45]:
def dataframe(x):
    index=np.where(df['Panel Name']==x)[0][0]
    return df.iloc[index]['POWER']

In [46]:
val = new_df['panel_name'].apply(lambda x: dataframe(x))

In [47]:
len(val)

759

In [48]:
new_df['power'] = val
val

0       23.4639
1       23.4639
2       23.4639
3       23.4639
4       22.2275
         ...
1003    37.9780
1004    36.0126
1005    36.0126
1006    36.0126
1007    36.0126
Name: panel_name, Length: 759, dtype: float64

In [49]:
df.iloc[5]['POWER']

22.2275

In [50]:
new_df.head()

  panel_name   image_name lebel time   LUX  TEMP (Celcius)    power
0    d-1-3-1  d-1-3-1.jpg     d    1  1350            27.0  23.4639
1    d-1-3-2  d-1-3-2.jpg     d    1  1350            27.0  23.4639
2    d-1-3-3  d-1-3-3.jpg     d    1  1350            27.0  23.4639
3    d-1-3-4  d-1-3-4.jpg     d    1  1350            27.0  23.4639
4    d-1-4-1  d-1-4-1.jpg     d    1  2380            27.1  22.2275

In [51]:
new_df.shape

(759, 7)

In [52]:
new_df.to_csv('metadataclean.csv')